-- MySQL Script generated by MySQL Workbench
-- mié 01 jun 2016 18:42:18 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Orto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Orto` ;

-- -----------------------------------------------------
-- Schema Orto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Orto` DEFAULT CHARACTER SET utf8 ;
USE `Orto` ;

-- -----------------------------------------------------
-- Table `Orto`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Doctor` (
  `idDoctor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `ci` INT UNSIGNED NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` INT UNSIGNED NULL,
  `spec_id` TINYINT UNSIGNED NOT NULL,
  `bank_account` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idDoctor`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `bank_account_UNIQUE` (`bank_account` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Orto`.`Speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Speciality` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Speciality` (
  `idSpeciality` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idSpeciality`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orto`.`Doctor_has_Speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Doctor_has_Speciality` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Doctor_has_Speciality` (
  `Doctor_idDoctor` INT UNSIGNED NOT NULL,
  `Speciality_idSpeciality` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Doctor_idDoctor`, `Speciality_idSpeciality`),
  INDEX `fk_Doctor_has_Speciality_Speciality1_idx` (`Speciality_idSpeciality` ASC),
  INDEX `fk_Doctor_has_Speciality_Doctor_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Doctor_has_Speciality_Doctor`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `Orto`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Speciality_Speciality1`
    FOREIGN KEY (`Speciality_idSpeciality`)
    REFERENCES `Orto`.`Speciality` (`idSpeciality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orto`.`Pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Pacient` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Pacient` (
  `idPacient` INT NOT NULL AUTO_INCREMENT,
  `name_pacient` VARCHAR(128) NOT NULL,
  `ci_pacient` INT UNSIGNED NOT NULL,
  `birth_date` TIMESTAMP NOT NULL,
  `sex` CHAR NOT NULL,
  `phone_pacient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPacient`),
  UNIQUE INDEX `ci_pacient_UNIQUE` (`ci_pacient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orto`.`Dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Dates` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Dates` (
  `Doctor_idDoctor` INT UNSIGNED NOT NULL,
  `Pacient_idPacient` INT NOT NULL,
  `date_consult` TIMESTAMP NOT NULL,
  PRIMARY KEY (`Doctor_idDoctor`, `Pacient_idPacient`),
  INDEX `fk_Doctor_has_Pacient_Pacient1_idx` (`Pacient_idPacient` ASC),
  INDEX `fk_Doctor_has_Pacient_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Doctor_has_Pacient_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `Orto`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Pacient_Pacient1`
    FOREIGN KEY (`Pacient_idPacient`)
    REFERENCES `Orto`.`Pacient` (`idPacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orto`.`Consult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Consult` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Consult` (
  `Doctor_idDoctor` INT UNSIGNED NOT NULL,
  `Pacient_idPacient` INT NOT NULL,
  `Description` VARCHAR(256) NULL,
  PRIMARY KEY (`Doctor_idDoctor`, `Pacient_idPacient`),
  INDEX `fk_Doctor_has_Pacient_Pacient2_idx` (`Pacient_idPacient` ASC),
  INDEX `fk_Doctor_has_Pacient_Doctor2_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Doctor_has_Pacient_Doctor2`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `Orto`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Pacient_Pacient2`
    FOREIGN KEY (`Pacient_idPacient`)
    REFERENCES `Orto`.`Pacient` (`idPacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orto`.`Consult_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orto`.`Consult_Type` ;

CREATE TABLE IF NOT EXISTS `Orto`.`Consult_Type` (
  `idConsult_Type` INT NOT NULL AUTO_INCREMENT,
  `description_type` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idConsult_Type`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
